# Generated by Django 4.1.4 on 2022-12-29 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video', models.FileField(upload_to=users.models.uservideouploadpath)),
                ('Category', models.CharField(max_length=50)),
                ('ChooseDate', models.DateTimeField(auto_now_add=True)),
                ('VideoTitle', models.TextField()),
                ('sumprice', models.FloatField()),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
