# Generated by Django 4.1.4 on 2022-12-28 14:54

import adminapp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='categoryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=50)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('InfoOfCategory', models.TextField()),
                ('adminId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='adminUploadvideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VideoTemplate', models.FileField(upload_to=adminapp.models.adminuploadpath)),
                ('VideoDetails', models.TextField(blank=True)),
                ('VideoPrice', models.FloatField()),
                ('offer', models.FloatField()),
                ('Discount', models.FloatField()),
                ('Activitystatus', models.CharField(max_length=20)),
                ('uploaddate', models.DateTimeField(auto_now_add=True)),
                ('AdminId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('CatId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.categorydetails')),
            ],
        ),
    ]
